// Mocks generated by Mockito 5.4.6 from annotations
// in my_manga_editor/test/feature/manga/provider/manga_providers_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:flutter_quill/quill_delta.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:my_manga_editor/feature/manga/model/manga.dart' as _i5;
import 'package:my_manga_editor/feature/manga/model/sync_status.dart' as _i7;
import 'package:my_manga_editor/feature/manga/repository/manga_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [MangaRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMangaRepository extends _i1.Mock implements _i2.MangaRepository {
  @override
  _i3.Future<String> createNewManga({String? name = '無名の傑作'}) =>
      (super.noSuchMethod(
        Invocation.method(
          #createNewManga,
          [],
          {#name: name},
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #createNewManga,
            [],
            {#name: name},
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #createNewManga,
            [],
            {#name: name},
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Stream<_i5.Manga?> getMangaStream(String? id) => (super.noSuchMethod(
        Invocation.method(
          #getMangaStream,
          [id],
        ),
        returnValue: _i3.Stream<_i5.Manga?>.empty(),
        returnValueForMissingStub: _i3.Stream<_i5.Manga?>.empty(),
      ) as _i3.Stream<_i5.Manga?>);

  @override
  _i3.Stream<List<_i5.Manga>> watchAllMangaList() => (super.noSuchMethod(
        Invocation.method(
          #watchAllMangaList,
          [],
        ),
        returnValue: _i3.Stream<List<_i5.Manga>>.empty(),
        returnValueForMissingStub: _i3.Stream<List<_i5.Manga>>.empty(),
      ) as _i3.Stream<List<_i5.Manga>>);

  @override
  _i3.Future<void> updateMangaName(
    String? id,
    String? name,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMangaName,
          [
            id,
            name,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateStartPage(
    String? id,
    _i5.MangaStartPage? value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateStartPage,
          [
            id,
            value,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteManga(String? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteManga,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  void saveDelta(
    int? id,
    _i6.Delta? delta,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #saveDelta,
          [
            id,
            delta,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i3.Future<_i6.Delta?> loadDelta(int? id) => (super.noSuchMethod(
        Invocation.method(
          #loadDelta,
          [id],
        ),
        returnValue: _i3.Future<_i6.Delta?>.value(),
        returnValueForMissingStub: _i3.Future<_i6.Delta?>.value(),
      ) as _i3.Future<_i6.Delta?>);

  @override
  _i3.Stream<_i6.Delta?> getDeltaStream(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getDeltaStream,
          [id],
        ),
        returnValue: _i3.Stream<_i6.Delta?>.empty(),
        returnValueForMissingStub: _i3.Stream<_i6.Delta?>.empty(),
      ) as _i3.Stream<_i6.Delta?>);

  @override
  _i3.Future<String> createNewMangaPage(String? mangaId) => (super.noSuchMethod(
        Invocation.method(
          #createNewMangaPage,
          [mangaId],
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #createNewMangaPage,
            [mangaId],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #createNewMangaPage,
            [mangaId],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Stream<_i5.MangaPage?> getMangaPageStream(String? pageId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMangaPageStream,
          [pageId],
        ),
        returnValue: _i3.Stream<_i5.MangaPage?>.empty(),
        returnValueForMissingStub: _i3.Stream<_i5.MangaPage?>.empty(),
      ) as _i3.Stream<_i5.MangaPage?>);

  @override
  _i3.Stream<_i5.MangaPage?> getMangaPageStreamWithMangaId(
    String? mangaId,
    String? pageId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getMangaPageStreamWithMangaId,
          [
            mangaId,
            pageId,
          ],
        ),
        returnValue: _i3.Stream<_i5.MangaPage?>.empty(),
        returnValueForMissingStub: _i3.Stream<_i5.MangaPage?>.empty(),
      ) as _i3.Stream<_i5.MangaPage?>);

  @override
  _i3.Stream<List<String>> watchAllMangaPageIdList(String? mangaId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchAllMangaPageIdList,
          [mangaId],
        ),
        returnValue: _i3.Stream<List<String>>.empty(),
        returnValueForMissingStub: _i3.Stream<List<String>>.empty(),
      ) as _i3.Stream<List<String>>);

  @override
  _i3.Future<void> reorderPages(
    String? mangaId,
    List<String>? pageIdList,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #reorderPages,
          [
            mangaId,
            pageIdList,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteMangaPage(String? pageId) => (super.noSuchMethod(
        Invocation.method(
          #deleteMangaPage,
          [pageId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Stream<_i7.SyncStatus> watchSyncStatus() => (super.noSuchMethod(
        Invocation.method(
          #watchSyncStatus,
          [],
        ),
        returnValue: _i3.Stream<_i7.SyncStatus>.empty(),
        returnValueForMissingStub: _i3.Stream<_i7.SyncStatus>.empty(),
      ) as _i3.Stream<_i7.SyncStatus>);

  @override
  _i3.Future<void> forceSyncAll() => (super.noSuchMethod(
        Invocation.method(
          #forceSyncAll,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<String> toMarkdown(String? mangaId) => (super.noSuchMethod(
        Invocation.method(
          #toMarkdown,
          [mangaId],
        ),
        returnValue: _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #toMarkdown,
            [mangaId],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #toMarkdown,
            [mangaId],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  void dispose() => super.noSuchMethod(
        Invocation.method(
          #dispose,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
