// Mocks generated by Mockito 5.4.6 from annotations
// in my_manga_editor_data/test/repository/app_config_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:my_manga_editor_data/service/firebase/firebase_service.dart'
    as _i2;
import 'package:my_manga_editor_data/service/firebase/model/cloud_app_config.dart'
    as _i4;
import 'package:my_manga_editor_data/service/firebase/model/cloud_delta.dart'
    as _i8;
import 'package:my_manga_editor_data/service/firebase/model/cloud_manga.dart'
    as _i5;
import 'package:my_manga_editor_data/service/firebase/model/cloud_manga_page.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFirebaseBatchWrapper_0 extends _i1.SmartFake
    implements _i2.FirebaseBatchWrapper {
  _FakeFirebaseBatchWrapper_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FirebaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseService extends _i1.Mock implements _i2.FirebaseService {
  @override
  _i3.Stream<_i4.CloudAppConfig?> watchAppConfig() => (super.noSuchMethod(
        Invocation.method(
          #watchAppConfig,
          [],
        ),
        returnValue: _i3.Stream<_i4.CloudAppConfig?>.empty(),
        returnValueForMissingStub: _i3.Stream<_i4.CloudAppConfig?>.empty(),
      ) as _i3.Stream<_i4.CloudAppConfig?>);

  @override
  _i3.Future<void> uploadManga(_i5.CloudManga? manga) => (super.noSuchMethod(
        Invocation.method(
          #uploadManga,
          [manga],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> uploadMangaPage(_i6.CloudMangaPage? page) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadMangaPage,
          [page],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteManga(String? mangaId) => (super.noSuchMethod(
        Invocation.method(
          #deleteManga,
          [mangaId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteMangaPage(
    String? mangaId,
    String? pageId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMangaPage,
          [
            mangaId,
            pageId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i5.CloudManga>> fetchUserMangas() => (super.noSuchMethod(
        Invocation.method(
          #fetchUserMangas,
          [],
        ),
        returnValue: _i3.Future<List<_i5.CloudManga>>.value(<_i5.CloudManga>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i5.CloudManga>>.value(<_i5.CloudManga>[]),
      ) as _i3.Future<List<_i5.CloudManga>>);

  @override
  _i3.Future<List<_i6.CloudMangaPage>> fetchMangaPages(String? mangaId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchMangaPages,
          [mangaId],
        ),
        returnValue:
            _i3.Future<List<_i6.CloudMangaPage>>.value(<_i6.CloudMangaPage>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i6.CloudMangaPage>>.value(<_i6.CloudMangaPage>[]),
      ) as _i3.Future<List<_i6.CloudMangaPage>>);

  @override
  _i3.Future<_i5.CloudManga?> fetchManga(String? mangaId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchManga,
          [mangaId],
        ),
        returnValue: _i3.Future<_i5.CloudManga?>.value(),
        returnValueForMissingStub: _i3.Future<_i5.CloudManga?>.value(),
      ) as _i3.Future<_i5.CloudManga?>);

  @override
  _i3.Future<_i6.CloudMangaPage?> fetchMangaPage(
    String? mangaId,
    String? pageId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchMangaPage,
          [
            mangaId,
            pageId,
          ],
        ),
        returnValue: _i3.Future<_i6.CloudMangaPage?>.value(),
        returnValueForMissingStub: _i3.Future<_i6.CloudMangaPage?>.value(),
      ) as _i3.Future<_i6.CloudMangaPage?>);

  @override
  _i3.Future<String> createManga(_i5.CloudManga? manga) => (super.noSuchMethod(
        Invocation.method(
          #createManga,
          [manga],
        ),
        returnValue: _i3.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #createManga,
            [manga],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #createManga,
            [manga],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<String> createMangaPage(
    String? mangaId,
    _i6.CloudMangaPage? page,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMangaPage,
          [
            mangaId,
            page,
          ],
        ),
        returnValue: _i3.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #createMangaPage,
            [
              mangaId,
              page,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #createMangaPage,
            [
              mangaId,
              page,
            ],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<void> updateManga(
    String? mangaId,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateManga,
          [
            mangaId,
            updates,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> addMangaTag(
    String? mangaId,
    String? tag,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addMangaTag,
          [
            mangaId,
            tag,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> removeMangaTag(
    String? mangaId,
    String? tag,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeMangaTag,
          [
            mangaId,
            tag,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateMangaPage(
    String? mangaId,
    String? pageId,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMangaPage,
          [
            mangaId,
            pageId,
            updates,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Stream<_i5.CloudManga?> watchManga(String? mangaId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchManga,
          [mangaId],
        ),
        returnValue: _i3.Stream<_i5.CloudManga?>.empty(),
        returnValueForMissingStub: _i3.Stream<_i5.CloudManga?>.empty(),
      ) as _i3.Stream<_i5.CloudManga?>);

  @override
  _i3.Stream<List<_i5.CloudManga>> watchAllMangas(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchAllMangas,
          [userId],
        ),
        returnValue: _i3.Stream<List<_i5.CloudManga>>.empty(),
        returnValueForMissingStub: _i3.Stream<List<_i5.CloudManga>>.empty(),
      ) as _i3.Stream<List<_i5.CloudManga>>);

  @override
  _i3.Stream<_i6.CloudMangaPage?> watchMangaPage(String? pageId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchMangaPage,
          [pageId],
        ),
        returnValue: _i3.Stream<_i6.CloudMangaPage?>.empty(),
        returnValueForMissingStub: _i3.Stream<_i6.CloudMangaPage?>.empty(),
      ) as _i3.Stream<_i6.CloudMangaPage?>);

  @override
  _i3.Stream<_i6.CloudMangaPage?> watchMangaPageWithMangaId(
    String? mangaId,
    String? pageId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchMangaPageWithMangaId,
          [
            mangaId,
            pageId,
          ],
        ),
        returnValue: _i3.Stream<_i6.CloudMangaPage?>.empty(),
        returnValueForMissingStub: _i3.Stream<_i6.CloudMangaPage?>.empty(),
      ) as _i3.Stream<_i6.CloudMangaPage?>);

  @override
  _i3.Stream<List<_i6.CloudMangaPage>> watchMangaPages(String? mangaId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchMangaPages,
          [mangaId],
        ),
        returnValue: _i3.Stream<List<_i6.CloudMangaPage>>.empty(),
        returnValueForMissingStub: _i3.Stream<List<_i6.CloudMangaPage>>.empty(),
      ) as _i3.Stream<List<_i6.CloudMangaPage>>);

  @override
  _i3.Future<String> createDelta(
    String? mangaId,
    _i8.CloudDelta? delta,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createDelta,
          [
            mangaId,
            delta,
          ],
        ),
        returnValue: _i3.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #createDelta,
            [
              mangaId,
              delta,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<String>.value(_i7.dummyValue<String>(
          this,
          Invocation.method(
            #createDelta,
            [
              mangaId,
              delta,
            ],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<void> updateDelta(
    String? mangaId,
    String? deltaId,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDelta,
          [
            mangaId,
            deltaId,
            updates,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteDelta(
    String? mangaId,
    String? deltaId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteDelta,
          [
            mangaId,
            deltaId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i8.CloudDelta>> fetchDeltas(String? mangaId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchDeltas,
          [mangaId],
        ),
        returnValue: _i3.Future<List<_i8.CloudDelta>>.value(<_i8.CloudDelta>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i8.CloudDelta>>.value(<_i8.CloudDelta>[]),
      ) as _i3.Future<List<_i8.CloudDelta>>);

  @override
  _i3.Future<_i8.CloudDelta?> fetchDelta(
    String? mangaId,
    String? deltaId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchDelta,
          [
            mangaId,
            deltaId,
          ],
        ),
        returnValue: _i3.Future<_i8.CloudDelta?>.value(),
        returnValueForMissingStub: _i3.Future<_i8.CloudDelta?>.value(),
      ) as _i3.Future<_i8.CloudDelta?>);

  @override
  _i3.Stream<_i8.CloudDelta?> watchDelta(
    String? mangaId,
    String? deltaId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchDelta,
          [
            mangaId,
            deltaId,
          ],
        ),
        returnValue: _i3.Stream<_i8.CloudDelta?>.empty(),
        returnValueForMissingStub: _i3.Stream<_i8.CloudDelta?>.empty(),
      ) as _i3.Stream<_i8.CloudDelta?>);

  @override
  _i3.Stream<List<_i8.CloudDelta>> watchDeltas(String? mangaId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchDeltas,
          [mangaId],
        ),
        returnValue: _i3.Stream<List<_i8.CloudDelta>>.empty(),
        returnValueForMissingStub: _i3.Stream<List<_i8.CloudDelta>>.empty(),
      ) as _i3.Stream<List<_i8.CloudDelta>>);

  @override
  _i2.FirebaseBatchWrapper batch() => (super.noSuchMethod(
        Invocation.method(
          #batch,
          [],
        ),
        returnValue: _FakeFirebaseBatchWrapper_0(
          this,
          Invocation.method(
            #batch,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeFirebaseBatchWrapper_0(
          this,
          Invocation.method(
            #batch,
            [],
          ),
        ),
      ) as _i2.FirebaseBatchWrapper);
}
