// Mocks generated by Mockito 5.4.6 from annotations
// in my_manga_editor_data/test/repository/manga_repository_tags_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:firebase_auth/firebase_auth.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:my_manga_editor_data/service/connectivity_service.dart' as _i11;
import 'package:my_manga_editor_data/service/firebase/auth_service.dart'
    as _i10;
import 'package:my_manga_editor_data/service/firebase/firebase_service.dart'
    as _i2;
import 'package:my_manga_editor_data/service/firebase/model/cloud_app_config.dart'
    as _i5;
import 'package:my_manga_editor_data/service/firebase/model/cloud_delta.dart'
    as _i9;
import 'package:my_manga_editor_data/service/firebase/model/cloud_manga.dart'
    as _i6;
import 'package:my_manga_editor_data/service/firebase/model/cloud_manga_page.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeFirebaseBatchWrapper_0 extends _i1.SmartFake
    implements _i2.FirebaseBatchWrapper {
  _FakeFirebaseBatchWrapper_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserMetadata_1 extends _i1.SmartFake implements _i3.UserMetadata {
  _FakeUserMetadata_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMultiFactor_2 extends _i1.SmartFake implements _i3.MultiFactor {
  _FakeMultiFactor_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIdTokenResult_3 extends _i1.SmartFake implements _i3.IdTokenResult {
  _FakeIdTokenResult_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserCredential_4 extends _i1.SmartFake
    implements _i3.UserCredential {
  _FakeUserCredential_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeConfirmationResult_5 extends _i1.SmartFake
    implements _i3.ConfirmationResult {
  _FakeConfirmationResult_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUser_6 extends _i1.SmartFake implements _i3.User {
  _FakeUser_6(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FirebaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseService extends _i1.Mock implements _i2.FirebaseService {
  @override
  _i4.Stream<_i5.CloudAppConfig?> watchAppConfig() => (super.noSuchMethod(
        Invocation.method(
          #watchAppConfig,
          [],
        ),
        returnValue: _i4.Stream<_i5.CloudAppConfig?>.empty(),
        returnValueForMissingStub: _i4.Stream<_i5.CloudAppConfig?>.empty(),
      ) as _i4.Stream<_i5.CloudAppConfig?>);

  @override
  _i4.Future<void> uploadManga(_i6.CloudManga? manga) => (super.noSuchMethod(
        Invocation.method(
          #uploadManga,
          [manga],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> uploadMangaPage(_i7.CloudMangaPage? page) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadMangaPage,
          [page],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteManga(String? mangaId) => (super.noSuchMethod(
        Invocation.method(
          #deleteManga,
          [mangaId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteMangaPage(
    String? mangaId,
    String? pageId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMangaPage,
          [
            mangaId,
            pageId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i6.CloudManga>> fetchUserMangas() => (super.noSuchMethod(
        Invocation.method(
          #fetchUserMangas,
          [],
        ),
        returnValue: _i4.Future<List<_i6.CloudManga>>.value(<_i6.CloudManga>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i6.CloudManga>>.value(<_i6.CloudManga>[]),
      ) as _i4.Future<List<_i6.CloudManga>>);

  @override
  _i4.Future<List<_i7.CloudMangaPage>> fetchMangaPages(String? mangaId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchMangaPages,
          [mangaId],
        ),
        returnValue:
            _i4.Future<List<_i7.CloudMangaPage>>.value(<_i7.CloudMangaPage>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i7.CloudMangaPage>>.value(<_i7.CloudMangaPage>[]),
      ) as _i4.Future<List<_i7.CloudMangaPage>>);

  @override
  _i4.Future<_i6.CloudManga?> fetchManga(String? mangaId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchManga,
          [mangaId],
        ),
        returnValue: _i4.Future<_i6.CloudManga?>.value(),
        returnValueForMissingStub: _i4.Future<_i6.CloudManga?>.value(),
      ) as _i4.Future<_i6.CloudManga?>);

  @override
  _i4.Future<_i7.CloudMangaPage?> fetchMangaPage(
    String? mangaId,
    String? pageId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchMangaPage,
          [
            mangaId,
            pageId,
          ],
        ),
        returnValue: _i4.Future<_i7.CloudMangaPage?>.value(),
        returnValueForMissingStub: _i4.Future<_i7.CloudMangaPage?>.value(),
      ) as _i4.Future<_i7.CloudMangaPage?>);

  @override
  _i4.Future<String> createManga(_i6.CloudManga? manga) => (super.noSuchMethod(
        Invocation.method(
          #createManga,
          [manga],
        ),
        returnValue: _i4.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #createManga,
            [manga],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #createManga,
            [manga],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<String> createMangaPage(
    String? mangaId,
    _i7.CloudMangaPage? page,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMangaPage,
          [
            mangaId,
            page,
          ],
        ),
        returnValue: _i4.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #createMangaPage,
            [
              mangaId,
              page,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #createMangaPage,
            [
              mangaId,
              page,
            ],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> updateManga(
    String? mangaId,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateManga,
          [
            mangaId,
            updates,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> addMangaTag(
    String? mangaId,
    String? tag,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #addMangaTag,
          [
            mangaId,
            tag,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> removeMangaTag(
    String? mangaId,
    String? tag,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #removeMangaTag,
          [
            mangaId,
            tag,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateMangaPage(
    String? mangaId,
    String? pageId,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMangaPage,
          [
            mangaId,
            pageId,
            updates,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Stream<_i6.CloudManga?> watchManga(String? mangaId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchManga,
          [mangaId],
        ),
        returnValue: _i4.Stream<_i6.CloudManga?>.empty(),
        returnValueForMissingStub: _i4.Stream<_i6.CloudManga?>.empty(),
      ) as _i4.Stream<_i6.CloudManga?>);

  @override
  _i4.Stream<List<_i6.CloudManga>> watchAllMangas(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchAllMangas,
          [userId],
        ),
        returnValue: _i4.Stream<List<_i6.CloudManga>>.empty(),
        returnValueForMissingStub: _i4.Stream<List<_i6.CloudManga>>.empty(),
      ) as _i4.Stream<List<_i6.CloudManga>>);

  @override
  _i4.Stream<_i7.CloudMangaPage?> watchMangaPage(String? pageId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchMangaPage,
          [pageId],
        ),
        returnValue: _i4.Stream<_i7.CloudMangaPage?>.empty(),
        returnValueForMissingStub: _i4.Stream<_i7.CloudMangaPage?>.empty(),
      ) as _i4.Stream<_i7.CloudMangaPage?>);

  @override
  _i4.Stream<_i7.CloudMangaPage?> watchMangaPageWithMangaId(
    String? mangaId,
    String? pageId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchMangaPageWithMangaId,
          [
            mangaId,
            pageId,
          ],
        ),
        returnValue: _i4.Stream<_i7.CloudMangaPage?>.empty(),
        returnValueForMissingStub: _i4.Stream<_i7.CloudMangaPage?>.empty(),
      ) as _i4.Stream<_i7.CloudMangaPage?>);

  @override
  _i4.Stream<List<_i7.CloudMangaPage>> watchMangaPages(String? mangaId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchMangaPages,
          [mangaId],
        ),
        returnValue: _i4.Stream<List<_i7.CloudMangaPage>>.empty(),
        returnValueForMissingStub: _i4.Stream<List<_i7.CloudMangaPage>>.empty(),
      ) as _i4.Stream<List<_i7.CloudMangaPage>>);

  @override
  _i4.Future<String> createDelta(
    String? mangaId,
    _i9.CloudDelta? delta,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createDelta,
          [
            mangaId,
            delta,
          ],
        ),
        returnValue: _i4.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #createDelta,
            [
              mangaId,
              delta,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<String>.value(_i8.dummyValue<String>(
          this,
          Invocation.method(
            #createDelta,
            [
              mangaId,
              delta,
            ],
          ),
        )),
      ) as _i4.Future<String>);

  @override
  _i4.Future<void> updateDelta(
    String? mangaId,
    String? deltaId,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDelta,
          [
            mangaId,
            deltaId,
            updates,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteDelta(
    String? mangaId,
    String? deltaId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteDelta,
          [
            mangaId,
            deltaId,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i9.CloudDelta>> fetchDeltas(String? mangaId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchDeltas,
          [mangaId],
        ),
        returnValue: _i4.Future<List<_i9.CloudDelta>>.value(<_i9.CloudDelta>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i9.CloudDelta>>.value(<_i9.CloudDelta>[]),
      ) as _i4.Future<List<_i9.CloudDelta>>);

  @override
  _i4.Future<_i9.CloudDelta?> fetchDelta(
    String? mangaId,
    String? deltaId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchDelta,
          [
            mangaId,
            deltaId,
          ],
        ),
        returnValue: _i4.Future<_i9.CloudDelta?>.value(),
        returnValueForMissingStub: _i4.Future<_i9.CloudDelta?>.value(),
      ) as _i4.Future<_i9.CloudDelta?>);

  @override
  _i4.Stream<_i9.CloudDelta?> watchDelta(
    String? mangaId,
    String? deltaId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchDelta,
          [
            mangaId,
            deltaId,
          ],
        ),
        returnValue: _i4.Stream<_i9.CloudDelta?>.empty(),
        returnValueForMissingStub: _i4.Stream<_i9.CloudDelta?>.empty(),
      ) as _i4.Stream<_i9.CloudDelta?>);

  @override
  _i4.Stream<List<_i9.CloudDelta>> watchDeltas(String? mangaId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchDeltas,
          [mangaId],
        ),
        returnValue: _i4.Stream<List<_i9.CloudDelta>>.empty(),
        returnValueForMissingStub: _i4.Stream<List<_i9.CloudDelta>>.empty(),
      ) as _i4.Stream<List<_i9.CloudDelta>>);

  @override
  _i2.FirebaseBatchWrapper batch() => (super.noSuchMethod(
        Invocation.method(
          #batch,
          [],
        ),
        returnValue: _FakeFirebaseBatchWrapper_0(
          this,
          Invocation.method(
            #batch,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeFirebaseBatchWrapper_0(
          this,
          Invocation.method(
            #batch,
            [],
          ),
        ),
      ) as _i2.FirebaseBatchWrapper);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i10.AuthService {
  @override
  _i4.Stream<_i3.User?> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i4.Stream<_i3.User?>.empty(),
        returnValueForMissingStub: _i4.Stream<_i3.User?>.empty(),
      ) as _i4.Stream<_i3.User?>);

  @override
  bool get isSignedIn => (super.noSuchMethod(
        Invocation.getter(#isSignedIn),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i4.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i3.User?> signInAnonymously() => (super.noSuchMethod(
        Invocation.method(
          #signInAnonymously,
          [],
        ),
        returnValue: _i4.Future<_i3.User?>.value(),
        returnValueForMissingStub: _i4.Future<_i3.User?>.value(),
      ) as _i4.Future<_i3.User?>);

  @override
  _i4.Future<_i3.User?> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i4.Future<_i3.User?>.value(),
        returnValueForMissingStub: _i4.Future<_i3.User?>.value(),
      ) as _i4.Future<_i3.User?>);

  @override
  _i4.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i11.ConnectivityService {
  @override
  _i4.Future<bool> isOnline() => (super.noSuchMethod(
        Invocation.method(
          #isOnline,
          [],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);

  @override
  _i4.Stream<bool> onConnectivityChanged() => (super.noSuchMethod(
        Invocation.method(
          #onConnectivityChanged,
          [],
        ),
        returnValue: _i4.Stream<bool>.empty(),
        returnValueForMissingStub: _i4.Stream<bool>.empty(),
      ) as _i4.Stream<bool>);
}

/// A class which mocks [User].
///
/// See the documentation for Mockito's code generation for more information.
class MockUser extends _i1.Mock implements _i3.User {
  @override
  bool get emailVerified => (super.noSuchMethod(
        Invocation.getter(#emailVerified),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isAnonymous => (super.noSuchMethod(
        Invocation.getter(#isAnonymous),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i3.UserMetadata get metadata => (super.noSuchMethod(
        Invocation.getter(#metadata),
        returnValue: _FakeUserMetadata_1(
          this,
          Invocation.getter(#metadata),
        ),
        returnValueForMissingStub: _FakeUserMetadata_1(
          this,
          Invocation.getter(#metadata),
        ),
      ) as _i3.UserMetadata);

  @override
  List<_i3.UserInfo> get providerData => (super.noSuchMethod(
        Invocation.getter(#providerData),
        returnValue: <_i3.UserInfo>[],
        returnValueForMissingStub: <_i3.UserInfo>[],
      ) as List<_i3.UserInfo>);

  @override
  String get uid => (super.noSuchMethod(
        Invocation.getter(#uid),
        returnValue: _i8.dummyValue<String>(
          this,
          Invocation.getter(#uid),
        ),
        returnValueForMissingStub: _i8.dummyValue<String>(
          this,
          Invocation.getter(#uid),
        ),
      ) as String);

  @override
  _i3.MultiFactor get multiFactor => (super.noSuchMethod(
        Invocation.getter(#multiFactor),
        returnValue: _FakeMultiFactor_2(
          this,
          Invocation.getter(#multiFactor),
        ),
        returnValueForMissingStub: _FakeMultiFactor_2(
          this,
          Invocation.getter(#multiFactor),
        ),
      ) as _i3.MultiFactor);

  @override
  _i4.Future<void> delete() => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<String?> getIdToken([bool? forceRefresh = false]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getIdToken,
          [forceRefresh],
        ),
        returnValue: _i4.Future<String?>.value(),
        returnValueForMissingStub: _i4.Future<String?>.value(),
      ) as _i4.Future<String?>);

  @override
  _i4.Future<_i3.IdTokenResult> getIdTokenResult(
          [bool? forceRefresh = false]) =>
      (super.noSuchMethod(
        Invocation.method(
          #getIdTokenResult,
          [forceRefresh],
        ),
        returnValue: _i4.Future<_i3.IdTokenResult>.value(_FakeIdTokenResult_3(
          this,
          Invocation.method(
            #getIdTokenResult,
            [forceRefresh],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i3.IdTokenResult>.value(_FakeIdTokenResult_3(
          this,
          Invocation.method(
            #getIdTokenResult,
            [forceRefresh],
          ),
        )),
      ) as _i4.Future<_i3.IdTokenResult>);

  @override
  _i4.Future<_i3.UserCredential> linkWithCredential(
          _i3.AuthCredential? credential) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkWithCredential,
          [credential],
        ),
        returnValue: _i4.Future<_i3.UserCredential>.value(_FakeUserCredential_4(
          this,
          Invocation.method(
            #linkWithCredential,
            [credential],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i3.UserCredential>.value(_FakeUserCredential_4(
          this,
          Invocation.method(
            #linkWithCredential,
            [credential],
          ),
        )),
      ) as _i4.Future<_i3.UserCredential>);

  @override
  _i4.Future<_i3.UserCredential> linkWithProvider(_i3.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkWithProvider,
          [provider],
        ),
        returnValue: _i4.Future<_i3.UserCredential>.value(_FakeUserCredential_4(
          this,
          Invocation.method(
            #linkWithProvider,
            [provider],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i3.UserCredential>.value(_FakeUserCredential_4(
          this,
          Invocation.method(
            #linkWithProvider,
            [provider],
          ),
        )),
      ) as _i4.Future<_i3.UserCredential>);

  @override
  _i4.Future<_i3.UserCredential> reauthenticateWithProvider(
          _i3.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #reauthenticateWithProvider,
          [provider],
        ),
        returnValue: _i4.Future<_i3.UserCredential>.value(_FakeUserCredential_4(
          this,
          Invocation.method(
            #reauthenticateWithProvider,
            [provider],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i3.UserCredential>.value(_FakeUserCredential_4(
          this,
          Invocation.method(
            #reauthenticateWithProvider,
            [provider],
          ),
        )),
      ) as _i4.Future<_i3.UserCredential>);

  @override
  _i4.Future<_i3.UserCredential> reauthenticateWithPopup(
          _i3.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #reauthenticateWithPopup,
          [provider],
        ),
        returnValue: _i4.Future<_i3.UserCredential>.value(_FakeUserCredential_4(
          this,
          Invocation.method(
            #reauthenticateWithPopup,
            [provider],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i3.UserCredential>.value(_FakeUserCredential_4(
          this,
          Invocation.method(
            #reauthenticateWithPopup,
            [provider],
          ),
        )),
      ) as _i4.Future<_i3.UserCredential>);

  @override
  _i4.Future<void> reauthenticateWithRedirect(_i3.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #reauthenticateWithRedirect,
          [provider],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i3.UserCredential> linkWithPopup(_i3.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkWithPopup,
          [provider],
        ),
        returnValue: _i4.Future<_i3.UserCredential>.value(_FakeUserCredential_4(
          this,
          Invocation.method(
            #linkWithPopup,
            [provider],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i3.UserCredential>.value(_FakeUserCredential_4(
          this,
          Invocation.method(
            #linkWithPopup,
            [provider],
          ),
        )),
      ) as _i4.Future<_i3.UserCredential>);

  @override
  _i4.Future<void> linkWithRedirect(_i3.AuthProvider? provider) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkWithRedirect,
          [provider],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i3.ConfirmationResult> linkWithPhoneNumber(
    String? phoneNumber, [
    _i3.RecaptchaVerifier? verifier,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #linkWithPhoneNumber,
          [
            phoneNumber,
            verifier,
          ],
        ),
        returnValue:
            _i4.Future<_i3.ConfirmationResult>.value(_FakeConfirmationResult_5(
          this,
          Invocation.method(
            #linkWithPhoneNumber,
            [
              phoneNumber,
              verifier,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i3.ConfirmationResult>.value(_FakeConfirmationResult_5(
          this,
          Invocation.method(
            #linkWithPhoneNumber,
            [
              phoneNumber,
              verifier,
            ],
          ),
        )),
      ) as _i4.Future<_i3.ConfirmationResult>);

  @override
  _i4.Future<_i3.UserCredential> reauthenticateWithCredential(
          _i3.AuthCredential? credential) =>
      (super.noSuchMethod(
        Invocation.method(
          #reauthenticateWithCredential,
          [credential],
        ),
        returnValue: _i4.Future<_i3.UserCredential>.value(_FakeUserCredential_4(
          this,
          Invocation.method(
            #reauthenticateWithCredential,
            [credential],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i3.UserCredential>.value(_FakeUserCredential_4(
          this,
          Invocation.method(
            #reauthenticateWithCredential,
            [credential],
          ),
        )),
      ) as _i4.Future<_i3.UserCredential>);

  @override
  _i4.Future<void> reload() => (super.noSuchMethod(
        Invocation.method(
          #reload,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> sendEmailVerification(
          [_i3.ActionCodeSettings? actionCodeSettings]) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendEmailVerification,
          [actionCodeSettings],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i3.User> unlink(String? providerId) => (super.noSuchMethod(
        Invocation.method(
          #unlink,
          [providerId],
        ),
        returnValue: _i4.Future<_i3.User>.value(_FakeUser_6(
          this,
          Invocation.method(
            #unlink,
            [providerId],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i3.User>.value(_FakeUser_6(
          this,
          Invocation.method(
            #unlink,
            [providerId],
          ),
        )),
      ) as _i4.Future<_i3.User>);

  @override
  _i4.Future<void> updatePassword(String? newPassword) => (super.noSuchMethod(
        Invocation.method(
          #updatePassword,
          [newPassword],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updatePhoneNumber(
          _i3.PhoneAuthCredential? phoneCredential) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePhoneNumber,
          [phoneCredential],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateDisplayName(String? displayName) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDisplayName,
          [displayName],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updatePhotoURL(String? photoURL) => (super.noSuchMethod(
        Invocation.method(
          #updatePhotoURL,
          [photoURL],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateProfile({
    String? displayName,
    String? photoURL,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [],
          {
            #displayName: displayName,
            #photoURL: photoURL,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> verifyBeforeUpdateEmail(
    String? newEmail, [
    _i3.ActionCodeSettings? actionCodeSettings,
  ]) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyBeforeUpdateEmail,
          [
            newEmail,
            actionCodeSettings,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
