// Mocks generated by Mockito 5.4.6 from annotations
// in my_manga_editor_data/test/repository/manga_repository_export_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:firebase_auth/firebase_auth.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:my_manga_editor_data/service/connectivity_service.dart' as _i10;
import 'package:my_manga_editor_data/service/firebase/auth_service.dart' as _i8;
import 'package:my_manga_editor_data/service/firebase/firebase_service.dart'
    as _i2;
import 'package:my_manga_editor_data/service/firebase/model/cloud_delta.dart'
    as _i7;
import 'package:my_manga_editor_data/service/firebase/model/cloud_manga.dart'
    as _i4;
import 'package:my_manga_editor_data/service/firebase/model/cloud_manga_page.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFirebaseBatchWrapper_0 extends _i1.SmartFake
    implements _i2.FirebaseBatchWrapper {
  _FakeFirebaseBatchWrapper_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FirebaseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseService extends _i1.Mock implements _i2.FirebaseService {
  @override
  _i3.Future<void> uploadManga(_i4.CloudManga? manga) => (super.noSuchMethod(
        Invocation.method(
          #uploadManga,
          [manga],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> uploadMangaPage(_i5.CloudMangaPage? page) =>
      (super.noSuchMethod(
        Invocation.method(
          #uploadMangaPage,
          [page],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteManga(String? mangaId) => (super.noSuchMethod(
        Invocation.method(
          #deleteManga,
          [mangaId],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteMangaPage(
    String? mangaId,
    String? pageId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteMangaPage,
          [
            mangaId,
            pageId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i4.CloudManga>> fetchUserMangas() => (super.noSuchMethod(
        Invocation.method(
          #fetchUserMangas,
          [],
        ),
        returnValue: _i3.Future<List<_i4.CloudManga>>.value(<_i4.CloudManga>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i4.CloudManga>>.value(<_i4.CloudManga>[]),
      ) as _i3.Future<List<_i4.CloudManga>>);

  @override
  _i3.Future<List<_i5.CloudMangaPage>> fetchMangaPages(String? mangaId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchMangaPages,
          [mangaId],
        ),
        returnValue:
            _i3.Future<List<_i5.CloudMangaPage>>.value(<_i5.CloudMangaPage>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i5.CloudMangaPage>>.value(<_i5.CloudMangaPage>[]),
      ) as _i3.Future<List<_i5.CloudMangaPage>>);

  @override
  _i3.Future<_i4.CloudManga?> fetchManga(String? mangaId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchManga,
          [mangaId],
        ),
        returnValue: _i3.Future<_i4.CloudManga?>.value(),
        returnValueForMissingStub: _i3.Future<_i4.CloudManga?>.value(),
      ) as _i3.Future<_i4.CloudManga?>);

  @override
  _i3.Future<_i5.CloudMangaPage?> fetchMangaPage(
    String? mangaId,
    String? pageId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchMangaPage,
          [
            mangaId,
            pageId,
          ],
        ),
        returnValue: _i3.Future<_i5.CloudMangaPage?>.value(),
        returnValueForMissingStub: _i3.Future<_i5.CloudMangaPage?>.value(),
      ) as _i3.Future<_i5.CloudMangaPage?>);

  @override
  _i3.Future<String> createManga(_i4.CloudManga? manga) => (super.noSuchMethod(
        Invocation.method(
          #createManga,
          [manga],
        ),
        returnValue: _i3.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #createManga,
            [manga],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #createManga,
            [manga],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<String> createMangaPage(
    String? mangaId,
    _i5.CloudMangaPage? page,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createMangaPage,
          [
            mangaId,
            page,
          ],
        ),
        returnValue: _i3.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #createMangaPage,
            [
              mangaId,
              page,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #createMangaPage,
            [
              mangaId,
              page,
            ],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<void> updateManga(
    String? mangaId,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateManga,
          [
            mangaId,
            updates,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> updateMangaPage(
    String? mangaId,
    String? pageId,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMangaPage,
          [
            mangaId,
            pageId,
            updates,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Stream<_i4.CloudManga?> watchManga(String? mangaId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchManga,
          [mangaId],
        ),
        returnValue: _i3.Stream<_i4.CloudManga?>.empty(),
        returnValueForMissingStub: _i3.Stream<_i4.CloudManga?>.empty(),
      ) as _i3.Stream<_i4.CloudManga?>);

  @override
  _i3.Stream<List<_i4.CloudManga>> watchAllMangas(String? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchAllMangas,
          [userId],
        ),
        returnValue: _i3.Stream<List<_i4.CloudManga>>.empty(),
        returnValueForMissingStub: _i3.Stream<List<_i4.CloudManga>>.empty(),
      ) as _i3.Stream<List<_i4.CloudManga>>);

  @override
  _i3.Stream<_i5.CloudMangaPage?> watchMangaPage(String? pageId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchMangaPage,
          [pageId],
        ),
        returnValue: _i3.Stream<_i5.CloudMangaPage?>.empty(),
        returnValueForMissingStub: _i3.Stream<_i5.CloudMangaPage?>.empty(),
      ) as _i3.Stream<_i5.CloudMangaPage?>);

  @override
  _i3.Stream<_i5.CloudMangaPage?> watchMangaPageWithMangaId(
    String? mangaId,
    String? pageId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchMangaPageWithMangaId,
          [
            mangaId,
            pageId,
          ],
        ),
        returnValue: _i3.Stream<_i5.CloudMangaPage?>.empty(),
        returnValueForMissingStub: _i3.Stream<_i5.CloudMangaPage?>.empty(),
      ) as _i3.Stream<_i5.CloudMangaPage?>);

  @override
  _i3.Stream<List<_i5.CloudMangaPage>> watchMangaPages(String? mangaId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchMangaPages,
          [mangaId],
        ),
        returnValue: _i3.Stream<List<_i5.CloudMangaPage>>.empty(),
        returnValueForMissingStub: _i3.Stream<List<_i5.CloudMangaPage>>.empty(),
      ) as _i3.Stream<List<_i5.CloudMangaPage>>);

  @override
  _i3.Future<String> createDelta(
    String? mangaId,
    _i7.CloudDelta? delta,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createDelta,
          [
            mangaId,
            delta,
          ],
        ),
        returnValue: _i3.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #createDelta,
            [
              mangaId,
              delta,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i3.Future<String>.value(_i6.dummyValue<String>(
          this,
          Invocation.method(
            #createDelta,
            [
              mangaId,
              delta,
            ],
          ),
        )),
      ) as _i3.Future<String>);

  @override
  _i3.Future<void> updateDelta(
    String? mangaId,
    String? deltaId,
    Map<String, dynamic>? updates,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateDelta,
          [
            mangaId,
            deltaId,
            updates,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> deleteDelta(
    String? mangaId,
    String? deltaId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteDelta,
          [
            mangaId,
            deltaId,
          ],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<List<_i7.CloudDelta>> fetchDeltas(String? mangaId) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchDeltas,
          [mangaId],
        ),
        returnValue: _i3.Future<List<_i7.CloudDelta>>.value(<_i7.CloudDelta>[]),
        returnValueForMissingStub:
            _i3.Future<List<_i7.CloudDelta>>.value(<_i7.CloudDelta>[]),
      ) as _i3.Future<List<_i7.CloudDelta>>);

  @override
  _i3.Future<_i7.CloudDelta?> fetchDelta(
    String? mangaId,
    String? deltaId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchDelta,
          [
            mangaId,
            deltaId,
          ],
        ),
        returnValue: _i3.Future<_i7.CloudDelta?>.value(),
        returnValueForMissingStub: _i3.Future<_i7.CloudDelta?>.value(),
      ) as _i3.Future<_i7.CloudDelta?>);

  @override
  _i3.Stream<_i7.CloudDelta?> watchDelta(
    String? mangaId,
    String? deltaId,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchDelta,
          [
            mangaId,
            deltaId,
          ],
        ),
        returnValue: _i3.Stream<_i7.CloudDelta?>.empty(),
        returnValueForMissingStub: _i3.Stream<_i7.CloudDelta?>.empty(),
      ) as _i3.Stream<_i7.CloudDelta?>);

  @override
  _i3.Stream<List<_i7.CloudDelta>> watchDeltas(String? mangaId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchDeltas,
          [mangaId],
        ),
        returnValue: _i3.Stream<List<_i7.CloudDelta>>.empty(),
        returnValueForMissingStub: _i3.Stream<List<_i7.CloudDelta>>.empty(),
      ) as _i3.Stream<List<_i7.CloudDelta>>);

  @override
  _i2.FirebaseBatchWrapper batch() => (super.noSuchMethod(
        Invocation.method(
          #batch,
          [],
        ),
        returnValue: _FakeFirebaseBatchWrapper_0(
          this,
          Invocation.method(
            #batch,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeFirebaseBatchWrapper_0(
          this,
          Invocation.method(
            #batch,
            [],
          ),
        ),
      ) as _i2.FirebaseBatchWrapper);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i8.AuthService {
  @override
  _i3.Stream<_i9.User?> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i3.Stream<_i9.User?>.empty(),
        returnValueForMissingStub: _i3.Stream<_i9.User?>.empty(),
      ) as _i3.Stream<_i9.User?>);

  @override
  bool get isSignedIn => (super.noSuchMethod(
        Invocation.getter(#isSignedIn),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i3.Future<void> initialize() => (super.noSuchMethod(
        Invocation.method(
          #initialize,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<_i9.User?> signInAnonymously() => (super.noSuchMethod(
        Invocation.method(
          #signInAnonymously,
          [],
        ),
        returnValue: _i3.Future<_i9.User?>.value(),
        returnValueForMissingStub: _i3.Future<_i9.User?>.value(),
      ) as _i3.Future<_i9.User?>);

  @override
  _i3.Future<_i9.User?> signInWithGoogle() => (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue: _i3.Future<_i9.User?>.value(),
        returnValueForMissingStub: _i3.Future<_i9.User?>.value(),
      ) as _i3.Future<_i9.User?>);

  @override
  _i3.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}

/// A class which mocks [ConnectivityService].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivityService extends _i1.Mock
    implements _i10.ConnectivityService {
  @override
  _i3.Future<bool> isOnline() => (super.noSuchMethod(
        Invocation.method(
          #isOnline,
          [],
        ),
        returnValue: _i3.Future<bool>.value(false),
        returnValueForMissingStub: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);

  @override
  _i3.Stream<bool> onConnectivityChanged() => (super.noSuchMethod(
        Invocation.method(
          #onConnectivityChanged,
          [],
        ),
        returnValue: _i3.Stream<bool>.empty(),
        returnValueForMissingStub: _i3.Stream<bool>.empty(),
      ) as _i3.Stream<bool>);
}
