// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIzOroMvjfTmrg0ckgyBIY61OHJXXSM_E',
    appId: '1:948924085739:web:e5de31d00cec9ad7a815ae',
    messagingSenderId: '948924085739',
    projectId: 'my-manga-editor',
    authDomain: 'my-manga-editor.firebaseapp.com',
    storageBucket: 'my-manga-editor.firebasestorage.app',
    measurementId: 'G-YQV4WSZGFV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6Qn6V2RmNxwzJV0I_OCHpQ2ozqUsjWzA',
    appId: '1:948924085739:android:b23952687331b4dca815ae',
    messagingSenderId: '948924085739',
    projectId: 'my-manga-editor',
    storageBucket: 'my-manga-editor.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0hejcG_tIg4COEWFtn7xtmlmGTm_tlSY',
    appId: '1:948924085739:ios:0638de170338fb49a815ae',
    messagingSenderId: '948924085739',
    projectId: 'my-manga-editor',
    storageBucket: 'my-manga-editor.firebasestorage.app',
    iosClientId: '948924085739-r6ji6m3r9emq3hg4tbhvo38ajspv77gi.apps.googleusercontent.com',
    iosBundleId: 'jp.firstforest.manga.editor.myMangaEditor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0hejcG_tIg4COEWFtn7xtmlmGTm_tlSY',
    appId: '1:948924085739:ios:0638de170338fb49a815ae',
    messagingSenderId: '948924085739',
    projectId: 'my-manga-editor',
    storageBucket: 'my-manga-editor.firebasestorage.app',
    iosClientId: '948924085739-r6ji6m3r9emq3hg4tbhvo38ajspv77gi.apps.googleusercontent.com',
    iosBundleId: 'jp.firstforest.manga.editor.myMangaEditor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIzOroMvjfTmrg0ckgyBIY61OHJXXSM_E',
    appId: '1:948924085739:web:286ecf76c8b1e457a815ae',
    messagingSenderId: '948924085739',
    projectId: 'my-manga-editor',
    authDomain: 'my-manga-editor.firebaseapp.com',
    storageBucket: 'my-manga-editor.firebasestorage.app',
    measurementId: 'G-TT9XN93VQ8',
  );

}