// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAO70VGLNcJQA1Ycv7R34adjD3WguDDhE4',
    appId: '1:411539508745:web:c06a0486d7afa0cf0432d8',
    messagingSenderId: '411539508745',
    projectId: 'my-manga-editor-dev',
    authDomain: 'my-manga-editor-dev.firebaseapp.com',
    storageBucket: 'my-manga-editor-dev.firebasestorage.app',
    measurementId: 'G-QKC6RNKGFH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBw19GXjHEbHbmMiVXFR6PBK33DyZJfSyI',
    appId: '1:411539508745:android:e0bdf5c6509bba360432d8',
    messagingSenderId: '411539508745',
    projectId: 'my-manga-editor-dev',
    storageBucket: 'my-manga-editor-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBW_XmMNVOSCrSZgRb3XSR9q7OihtNKPv0',
    appId: '1:411539508745:ios:3c4da061dd7058cf0432d8',
    messagingSenderId: '411539508745',
    projectId: 'my-manga-editor-dev',
    storageBucket: 'my-manga-editor-dev.firebasestorage.app',
    iosBundleId: 'jp.firstforest.manga.editor.myMangaEditor',
  );
}
